controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# app_user_adresses_delete:
#     path: /user/{id}/adresses/{id_adresse}/delete
#     controller: App\Controller\UserController::removeAdresse
#     methods: ['POST']
